#ENC[AES256_GCM,data:/MlabdTcbSKVg/X0UOyGWXBdu+Y28loARjtp1w==,iv:BmO/kMsQ5Px27gunfAUNz2eojlbkT0nRyyo/Vb5X0FA=,tag:myaN0edFlqv00t/jE8SQ7A==,type:comment]
#ENC[AES256_GCM,data:XU5M715WLRYXS6RbrhgrUYflDpyC2s4mMJD4AmA21ZMoJ0MSRyGD6SPEyoy4bA==,iv:QOmYl0ro4i7+lD88h8a4WrK6q2KpTqVqtgGW3It8uyU=,tag:fRRgyyFm7MJEwaDpb54tWg==,type:comment]
#
#ENC[AES256_GCM,data:kND7s8MuoT2HqB/GI8QxzolS0LCSZA/FYiqlzikYaAlKFdgitQ==,iv:RenMVVbQMMTFAQyNaq7CVxCnzr4i5/wPUs3uDPoxGZ4=,tag:mbdfCAQ6Yxn9tZVn/dM8SQ==,type:comment]
#ENC[AES256_GCM,data:XmoXbmipQwV8Rh+K4zB02I+oGE2gwftqAwUTZu7rFKnaF1OVombdurK8,iv:QfjrpnF3xJnU3n0TBgKrleNAZflORvfU/5VNbyUicn0=,tag:CrIumeEB9bukISa6hnYHBw==,type:comment]
#ENC[AES256_GCM,data:P6IqT2yRySjVmcHBfhjpUc6c1p5OctW+gcwOTAljPRYAWqGqIEUZVXIxeIMW,iv:9kceakEBJ9+uLg+V0aUozMOefgYWJMU+4+u/8fc5yCI=,tag:yxE1AlQv9dzfMsrU6CPrSg==,type:comment]
config:
    cloudflare:apiToken:
        secret: ENC[AES256_GCM,data:/S4z5Q==,iv:eX1ecL6bRIHruT+fj0D/wiBxKv6NoqBRgqcq+RcDDuo=,tag:EADSPjaSI4YJ3jkEiBh9Jg==,type:bool]
        value: ENC[AES256_GCM,data:821gHe34kV1gDjUJHoj7UfzL2foGbKuu3jXKlH+UHJlWb8yIYTfvvQ==,iv:lALfMvLXGI27jJPGmmC3no61Gn0gOJkOkNR2mKCMEtw=,tag:Gg3caDL7R5PFm/38nfIMkg==,type:str]
    container-registry:domain:
        value: ENC[AES256_GCM,data:xuE7QHsjBrZle/om5OSN5Ts6WpnT,iv:mCt/9LMgf5EgfnCi2Ujh5vfxyz91tq8Ms+MsUEdwTH4=,tag:NMyfu/pg0EI5peCP713o9A==,type:str]
    container-registry:username:
        value: ENC[AES256_GCM,data:uN7d5LA=,iv:3bqKDYZ3AhtBrK49CaYXts9n8RSLbjFUwfkmPJEhFmA=,tag:m70tDKG2FTlId9KU+798/w==,type:str]
    homelab:cloudflareAccountId:
        value: ENC[AES256_GCM,data:YcOjYCy0WWmX4/aqIzXXpWhAiATYzNqamSQXhNtqVbg=,iv:XQvzoRUG05LJdNTaKajrjFPcowp4mY80YdPV/W/GpwE=,tag:bqXKy9ykXX6qt9awHIb+ug==,type:str]
    homelab:cloudflareZoneId:
        value: ENC[AES256_GCM,data:wRySxFgJAZnC4jrUpCR5No9d3SBknWKlWGpVCuftgU8=,iv:/5S18tpJxyQFhaBEjasJ7rG8lJ0nlQ2MkGfiNYT8n8I=,tag:1o0knYZrhmdV5EgVVnOgPg==,type:str]
    homelab:container-registry:
        value: ENC[AES256_GCM,data:my6f4zJTJ9PcVK1x2RdRKp1oJjyuDmpNjwcRhJwUtUMJ8iua26nN9r0=,iv:ZWgj56txX4Pkux6AvVQy70REI+u50P9D5QmWfWZmxBY=,tag:kdi56UXegnAUzh4nRWrB4g==,type:str]
    homelab:domain:
        value: ENC[AES256_GCM,data:GoJcETY1DAY/bzhV,iv:Zw7fHnaK2cFMeaD/XHgoBsX0c60zufhlu1pav/Y5a+s=,tag:LJdMMn781oS0bPGPuUnLWA==,type:str]
    homelab:email:
        value: ENC[AES256_GCM,data:D0L5Htxa20EOHR2aUQfVzx5X,iv:8Rq1Z3FiA8qJmwc4YA44F8CbIF7xeinrL8/Ce/i42+M=,tag:H+phmpSaO1Gbahg2KiU1Qg==,type:str]
    homelab:pulumiAccessToken:
        secret: ENC[AES256_GCM,data:v34YcA==,iv:W2lzbduQlLGS2OqqYbPDEqLTSfzJhNRAuFE59EmHrqI=,tag:HpDjS0Q2JfHZrUcLMoDUwg==,type:bool]
        value: ENC[AES256_GCM,data:FIOOkkKtr9JHzZ2HT4xDJbqO36LxE6dzJVRKBlCgZaEWolJPzy9iyqJT7KM=,iv:8FAoRJdOn4qKuCXZc8Qh1Y4OrQlf364+7oDjOk/vcLo=,tag:1cbA+m8Uanr4aNr0boko7A==,type:str]
    homelab:pulumiOrganization:
        value: ENC[AES256_GCM,data:cRBpteewp7Sv,iv:XXQrzKPJQQjyeiVtfK3PkFcGyKmPbAeg9nr2NfajY00=,tag:P0Xv0IzMUXw/gTIu7/OWuw==,type:str]
    homelab:skipClusterIssuer:
        value: ENC[AES256_GCM,data:PtmpAw==,iv:DHqAmgXcnUJpoetCpH5A142VLHyTOalTePaozHThU/8=,tag:/kItkNpKcET7wcmid/b15g==,type:str]
    longhorn:backupAccessKeyId:
        secret: ENC[AES256_GCM,data:jIerwA==,iv:btOv6nAxIU14NRbBNLPwS30XAhnnM0WIWyBrwcH98Zg=,tag:y+DO1uMpFH7HY8vqzrNJ5A==,type:bool]
        value: ENC[AES256_GCM,data:9VZyNrWcdujuXOOw2JPUAQU8xnTxHimcXTKPeg7wpg4=,iv:epAZxsWeT8PKpPy2xDsig10FZtAmYy7dx7fHZ9BWVnQ=,tag:OH7K/hsu9getJIq7jPQPlg==,type:str]
    longhorn:backupSecretAccessKey:
        secret: ENC[AES256_GCM,data:oWIsVQ==,iv:9wvkoZvltS5hTayvBQ3A3lPDjBIffiWL2Zuyc3Ssvuc=,tag:toiN33MOqy1kqOEDjuDEBQ==,type:bool]
        value: ENC[AES256_GCM,data:6VDj2+6qeigoE5rSy/2dXBd+211iawf5usku2aGNgaJwMfcJCx2qXnlexlLuEOTaKaKM41YAUHr4UKlFJVejfQ==,iv:TPu1xF9iFRXV7aDJ8KXiYdIPlCFulC5AnHVmWj1e/MQ=,tag:4AQCf5mPxZ1LgfK7I+2CIw==,type:str]
esc_environments:
    mrsimpson_homelab_dev:
        name: ENC[AES256_GCM,data:yi7gt13TYW+PE/DtyxpaimYcEACp,iv:kiWLrSNIcH3bIfMfMWZhAQ0tCEjiKZhkwG9VNtlGma8=,tag:zKzXv1Kwi0amnpYaXC9Xng==,type:str]
        values:
            github-credentials:
                token: ENC[AES256_GCM,data:gHfbkB3aTwTsPsGV0CdWGIBMFONCuosy8T+YRQR/g4+jopZvDjxZBA==,iv:nScNH5yNI5PSlg9db/xtLr23bwd4Mg8cZAIMbu9Gb1A=,tag:1DXR8BV6sKfI1q67Cnqo+Q==,type:str]
                username: ENC[AES256_GCM,data:u/gck8VytwGx,iv:dWMioeG9hYAbVNDoO+WMDZd27Gep6AhYhI7Ft9WjN2U=,tag:upNdtywVk/iRLLHwjCQuUw==,type:str]
            github-token: ENC[AES256_GCM,data:g1aRYQT/eSNiYx0W1zAKQnPABx5KIiLTgQ+CDs/WiL7OcgTRZM8E3w==,iv:on8HJhEcl42HNm+CGX+lK/BINZljkxr2z2jEbNp3SeI=,tag:W0OPwez7ca3xcpivnFDpjg==,type:str]
            github-username: ENC[AES256_GCM,data:uMVsLnnoSjP4,iv:RW6Z+At2H3wNeRgOUg8i3b8toCJaYHdqR53We3STWXQ=,tag:IOvZCcKJOK4t8QRzhj1nhg==,type:str]
sops:
    age:
        - recipient: age1fleshqd626lkpwd6p5y3wwwuz99ky0e5s6jwr07ssvezxn4924uq02qerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YnREOTZPMldJVy9vNHBT
            TXJIY04wajA0NU1aMUEyRlRaSEVKOEtTNmc4CjFYN3dQR3lYeDNZZkpXUlFYZCtO
            U1NHUXA5dUJZU0V3RlMyQlFHRE5BSDQKLS0tIEUvcytaK1dKQUJFOC9BTC9HY2lk
            ZGNXa29oNGZaQmFzQXZnY3NBS3FGWUUKmX5K5OhiiWBxT0FFFKd5NgxI1rsH/zh0
            VLfwt3rRM1yZ+yOmzAdkFoBgJE//BtQtjQRxUkVotQ3L9t1yy7ZTsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T23:05:39Z"
    mac: ENC[AES256_GCM,data:pltAkmLpMnKBSycOwu/LrHDPYLNlv9QetZQGqDyQHffa///ywRBX9U+VDi+1tD4eljmPejo29ERZXR6iuXmmqTIqY00skLi/r/G9CFhT3n2PW0eVIGO+H5pbr2GMAaRY5tLPtTkowlcgJ9YPTT3cn7gplypqbppGSaeJf3uttD8=,iv:4OsA8Lit2kpZTRyUW2YGdaYw9FJ9MjNeSlDffJkiW+M=,tag:0yRKscqVL6roUTTXwKRkLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
