#ENC[AES256_GCM,data:qmZ8k+G/9JX+Vi+dPaSBtK2hDRegmfaDMXlByQ==,iv:ldKDZ/zSp8PXBtNoUk/7eUjwBwf1Edsnf1X3fmhpv0o=,tag:rKXvcqH1g+5Wwz8OyGj8Ww==,type:comment]
#ENC[AES256_GCM,data:SqBGV+lpHAwlbcYf2bsROftzEq95bpgyqjZQ4NGczf5ziBeZxEcEyYupYxMThg==,iv:lLSE8SUhH7gIK3eEhK6fEGlEHxoxSvCR1dT1jESRGmE=,tag:HK8ziVuvzYn3V9KFgpf5/A==,type:comment]
#
#ENC[AES256_GCM,data:DS14GXSmgMliPl9c06PKrlvB1TIDjFiJ79L55y+J09584sDpGg==,iv:AxSPYo12iPUA2NePV4c68eDBWxfnLPfaepYvz7LPM7Y=,tag:mlOpuDC7xJGFx2GNbAviPw==,type:comment]
#ENC[AES256_GCM,data:LrX6W9QkX205TwFlG1h3LV5zZ3Ce0RnUNKAEgybgwnt9f4tUKVXUJeET,iv:mzzp64YF2lp/BGPSEFz82lO6iDJF2jt82Bz+7UD5Lgs=,tag:Uj/qJhsIZG58SA1bXW50hQ==,type:comment]
#ENC[AES256_GCM,data:Rw1V2GDhMUT4133m7R5cZFrM51L3xRCv4rTzuA4c0ZC0vAXn8facriCU/OMv,iv:PQpOUbLIkU6t7uN+trJObJNtZk2uIdY8XMRR342hH20=,tag:wX+zx+XwnTFQmEc4jW3QIw==,type:comment]
config:
    cloudflare:apiToken:
        secret: ENC[AES256_GCM,data:aJAVhA==,iv:3WI4+XdppaqJDIMyD6Wvs9HCOcbJwhZTzlcRzo1MbPE=,tag:WLIuvg7r0yuLNhQ3vo36bg==,type:bool]
        value: ENC[AES256_GCM,data:NLKQJVeY9LBXduzJu9J+B9BI+VMI7QUodnlSj4PKXLuqvzrlljbrmw==,iv:TMQtouo2WViV8rREnomGYLwmcAt9dNKBvKUtCV7VCkg=,tag:rLb943mgJL7KEAqt+MEdNg==,type:str]
    container-registry:domain:
        value: ENC[AES256_GCM,data:kleKKPu2eK4/aKHD4bu+tsn1BbZa,iv:d8pSS4hqtcDD5nGXp8P0nNdQ2obH3mD1TZVLD0sexxM=,tag:73h0fUPkx3kpxChD2yVGBA==,type:str]
    container-registry:username:
        value: ENC[AES256_GCM,data:WUVaN+Y=,iv:3lYCpn82eVQzNgjmxN8aWtll7l/0+cdod5XlslY0BeM=,tag:jsp8JjeVUwJHZcOPXOWwVA==,type:str]
    homelab:cloudflareAccountId:
        value: ENC[AES256_GCM,data:0ygaB4BgMn/NDTW1oVR+53PHePhRQHdZ/Drx2/GizO8=,iv:BQQ7CCE5vnDa2OAOu2+pm12gUcSjEeP2dD//kb/f038=,tag:lC942vVdCS5pMo0OBuTqkQ==,type:str]
    homelab:cloudflareZoneId:
        value: ENC[AES256_GCM,data:6d6HIDvAZIS+KgM80TFuBrIg1PJLWVkVyyxzwNQZ6lA=,iv:KX8mQ6PDlgxXqUYR5ZH2c8tjbh11v4okS/+2SYvpkXo=,tag:nG4gXanTF8lGewKqD4En6Q==,type:str]
    homelab:container-registry:
        value: ENC[AES256_GCM,data:rhuCJ5bNoisdoWTQ00titMR4KzE3ObWMpc7PER6A9ktZL1vmBtw7S6E=,iv:v5LmiAiU3JUfQOzbtLgtMyA/7xZY2Am+IntretKKv5s=,tag:xxoLJlBR2rGRP/GYjwJNaA==,type:str]
    homelab:domain:
        value: ENC[AES256_GCM,data:FpamyRRwdcce5SAh,iv:Yafj6PdD8QNCC6X92vAWrjba5fE4SLEtIv124nHbP8w=,tag:gDmkirb2JFVuMRv1izgcsw==,type:str]
    homelab:email:
        value: ENC[AES256_GCM,data:6VNHtExQp0lZppbJ49ZlscWX,iv:eTzPF/6/mycLaz+7aUW/9m8KUoeQSPHsgqaX1ifG1DI=,tag:O395AUJ98Mr9/Uc0vHhqKg==,type:str]
    homelab:pulumiAccessToken:
        secret: ENC[AES256_GCM,data:WxzTgA==,iv:2yVOkUh6Up9d0s+dOZWFKAKTzEKrJ4w3HYrQGWLfe+g=,tag:DBq22QzIrHHHE/GFEUWEkw==,type:bool]
        value: ENC[AES256_GCM,data:vdp2Bjx8EXbh9tRAOCOAlPJLYSO890QRfRTDVCB5zzAIImsngtCzybTxa0k=,iv:6AGXWwAhf4gcgD6TQuc4iqag6YV+hqdpFpdGHtMtX0U=,tag:jnmA0GCZwfrnPyvWUa1DSg==,type:str]
    homelab:pulumiOrganization:
        value: ENC[AES256_GCM,data:wg1F/pDWz7h/,iv:SCL4hQKro1TJ9s7NTZKBVFe9GnYCkmW+xfdFaT66fHs=,tag:p/Zd+uWxW0W8XMVzS0/iEA==,type:str]
    homelab:skipClusterIssuer:
        value: ENC[AES256_GCM,data:0Vih7A==,iv:4hCj1+Uo3rrX3qDJv3Fzb4I/jM2zBSyAbeS8+kd0WHw=,tag:B+zKfksnc/3WMEY2EABEiA==,type:str]
    longhorn:backupAccessKeyId:
        secret: ENC[AES256_GCM,data:yfgIYg==,iv:FbiD2X9/TmV4v1pNknXdhEux79q8f23DVPgN016KSSc=,tag:NMHpEdDnBzP6SN9HoynP2Q==,type:bool]
        value: ENC[AES256_GCM,data:/W73w7qsQZSL9m2cvE7/D6+zP7I3zndd+PaA7xQLZOg=,iv:yiODEW4+ENK8DrmRr74mTdvH+LAPtqt2+QcaXDGC/9M=,tag:AKwDzK8B0E8dXcvoJ3OHAg==,type:str]
    longhorn:backupSecretAccessKey:
        secret: ENC[AES256_GCM,data:ZLHM3w==,iv:LQ75xbN9jHqa3NPR+pEJqhVTpFgLUe7SvEmcbFgJOQs=,tag:/aUlkMeaUINn6UqfRxAvWQ==,type:bool]
        value: ENC[AES256_GCM,data:bpOz7OXYnBM7/IPp6QEOIQJrsqMv3RpWAIDJF4msBe8qgfX5DXWik22SdAT7m2qjl657GYjv5BqAdhIVDzQBMw==,iv:/RrnV208SKwZXpfyMpHRlnRJ73amckDR8QBrv3kgItc=,tag:5woGavDBLybJ1k7OFIZ8dA==,type:str]
esc_environments:
    mrsimpson_homelab_dev:
        name: ENC[AES256_GCM,data:EBYk130vVDdIfXBbdQzxPrHcis3A,iv:qjQAoAVnXUXzYk7nzF9MPGoJvxFoyT7YMnH2VYp/7Tw=,tag:8S3vTSn6yX65dzbVNJxFQw==,type:str]
        values:
            github-credentials:
                token: ENC[AES256_GCM,data:8Tp9ck34deOqF3mBuH5MBdrrP/V8WPZ2DAGtVJmY7V6B4mdVn3eYJQ==,iv:8rdldPOtQth1Rwlr11JzajuopbgZsKO/JowoGMrNb6Q=,tag:CdUiBcXJ556uOFU762WWeA==,type:str]
                username: ENC[AES256_GCM,data:KOUoSN2RLL2z,iv:py+xGSJB777Vml9CF788H6CvZ1g3NigsFNGMeqzgrVM=,tag:Dl85q4TzFQRRlP61v7zp+w==,type:str]
            github-token: ENC[AES256_GCM,data:L+FzOP7y1QpacOjdZP1Ep6I6L4FjDSgQXH8oX3rIzGTSzFVarNFShw==,iv:aTNHlLCHcqvOVSLNS/cQUivXDJ2Z5dfgiKgnX8gHuW0=,tag:AjkMD6ka5/XECW9trgkiFw==,type:str]
            github-username: ENC[AES256_GCM,data:GeCS8rbY1Xyv,iv:GBfuth8zFdv7iNX1kC9LKuRND0Q6LlwwAXMmL0+Rkso=,tag:gDgzQa/CIXJZvDzrv5NIbQ==,type:str]
sops:
    age:
        - recipient: age1fleshqd626lkpwd6p5y3wwwuz99ky0e5s6jwr07ssvezxn4924uq02qerp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NThGUVhUbm1KZURjR3hR
            MmR0ZmZXTC9vMVFTV3doOUY3bFBSaWgvM3pBCnBySmYxRkdpSERQR1VQVVUwTkZJ
            SDB1TTQ0ejd5NlVNWlpkck0yWlU1cTAKLS0tIElkaHVYdk9wQStZUnJacW0wQ09Z
            N2wzYXR4WHdrMkF0bTlzTEh6c3hPdkEKmBrxh78MMElKWuZnNu8Cmlv0toVkNloM
            XGtUro11yeakfg/2T+POO3oH3T1LBA2gq0ghwhJrWlLDadpWThuvrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T23:12:55Z"
    mac: ENC[AES256_GCM,data:r/pPwakMtFqE623PFnJWii6N57BSchZqwJu0O8nNQtDSMhdriy6wr4S4MNGaw1Xtya+Ktppo8F3mPJ9Dnb0vwn8HrbBQSwwJiOt6/tSpItKcLs1dlnypB8gxZXCsBNH5g99g7uJWZYdZCJ2ZsD+iaT2LtY/mPz1w1nl0fPuT5dM=,iv:p3qHW7fIoFj+fP2UylWD1LrzsveTKTqtYQB+BWLBDKw=,tag:zW2Utk5iuhzF3Yj8/ibqnw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
